const culture_en = {
    account: 'YOUR ACCOUNT',
    profileSubtitle: 'Your information, all in one place.',
    editProfile: 'Edit profile',
    preferences: 'Preferences & support',
    otherVehicles: 'Other vehicles',
    seats: 'seats',
    noVehiclesSub: 'Your assigned vehicles will appear here.',
    close: 'Close',
    retry: 'Try again',
    loadError: 'Your profile could not be loaded.',
    connectionHint: 'Check your connection and try again.',
    photoError: 'Your photo could not be updated. Please try again.',
    cameraPermission: 'Allow camera access in your device settings to take a profile photo.',
    uploading: 'Uploading photo',
    supportError: 'The support page could not be opened.',
    myProfile: 'My Profile',
    hello: 'Hello',
    help: 'Help',
    settings: 'Settings',
    logout: 'Sign Out',
    completed: 'Completed',
    late: 'Late',
    canceled: 'Cancel',
    vehicles: 'Vehicles',
    companies: 'Companies',
    ok: 'OK',
    driver: 'Driver',
    activeVehicle: 'Active Vehicle',
    usedVehicle: 'Active Vehicle',
    change: 'Change',
    myCars: 'My Vehicles',
    accountSettings: 'Account & Documents',
    driverInformation: 'Driver Information',
    myPersonalInformations: 'Personal Information',
    personalInfoSub: 'Name, phone, email & password',
    myDocuments: 'My Documents',
    documentsSub: 'Driver license & permits',
    institutionsIServe: 'Institutions I Serve',
    companiesSub: 'Partner transfer companies',
    languageSelect: 'Language',
    languageSub: 'Change app language',
    supportHelp: 'Support & Help',
    supportSub: 'Customer & driver assistance',
    changeProfilePhoto: 'Change Profile Photo',
    takeAPhoto: 'Take a Photo',
    takePhotoSub: 'Capture a new profile image with camera',
    chooseFromLibrary: 'Choose From Library',
    choosePhotoSub: 'Select an image from device gallery',
    failed: 'Failed!',
    successful: 'Successful',
    useCar: 'Active',
    document: 'Documents',
    warning: 'Sign Out',
    logOutText: 'Are you sure you want to sign out from your account?',
    rating: 'Rating',
    noVehicles: 'No vehicles registered.',
    appVersion: 'App Version',
};

const culture_tr = {
    account: 'HESABIM',
    profileSubtitle: 'Tüm bilgileriniz, tek bir yerde.',
    editProfile: 'Profili düzenle',
    preferences: 'Tercihler ve destek',
    otherVehicles: 'Diğer araçlar',
    seats: 'kişi',
    noVehiclesSub: 'Size tanımlanan araçlar burada görünecek.',
    close: 'Kapat',
    retry: 'Tekrar dene',
    loadError: 'Profiliniz yüklenemedi.',
    connectionHint: 'Bağlantınızı kontrol edip tekrar deneyin.',
    photoError: 'Fotoğrafınız güncellenemedi. Lütfen tekrar deneyin.',
    cameraPermission: 'Profil fotoğrafı çekmek için cihaz ayarlarından kamera erişimine izin verin.',
    uploading: 'Fotoğraf yükleniyor',
    supportError: 'Destek sayfası açılamadı.',
    myProfile: 'Profilim',
    hello: 'Merhaba',
    help: 'Destek',
    settings: 'Ayarlar',
    logout: 'Çıkış Yap',
    completed: 'Tamamlandı',
    late: 'Gecikti',
    canceled: 'Vazgeç',
    vehicles: 'Araçlar',
    companies: 'Şirketler',
    ok: 'Tamam',
    driver: 'Sürücü',
    activeVehicle: 'Aktif Kullanılan Araç',
    usedVehicle: 'Aktif Kullanılan Araç',
    change: 'Değiştir',
    myCars: 'Araçlarım',
    accountSettings: 'Hesap ve belgeler',
    driverInformation: 'Sürücü Bilgileri',
    myPersonalInformations: 'Kişisel Bilgilerim',
    personalInfoSub: 'İletişim ve hesap bilgileriniz',
    myDocuments: 'Belgelerim',
    documentsSub: 'Sürücü ve yetki belgeleriniz',
    institutionsIServe: 'Bağlı kurumlar',
    companiesSub: 'Hizmet verdiğiniz transfer şirketleri',
    languageSelect: 'Dil Seçimi',
    languageSub: 'Uygulama dil tercihi',
    supportHelp: 'Yardım merkezi',
    supportSub: 'İhtiyaç duyduğunuzda yanınızdayız',
    changeProfilePhoto: 'Profil Fotoğrafını Değiştir',
    takeAPhoto: 'Fotoğraf Çek',
    takePhotoSub: 'Kamera ile yeni profil fotoğrafı çekin',
    chooseFromLibrary: 'Galeriden Seç',
    choosePhotoSub: 'Cihazınızın albümünden bir görsel seçin',
    failed: 'Başarısız!',
    successful: 'Başarılı',
    useCar: 'Aktif',
    document: 'Araç Belgeleri',
    warning: 'Çıkış Yap',
    logOutText: 'Oturumunuzu kapatmak istediğinize emin misiniz?',
    rating: 'Puan',
    noVehicles: 'Kayıtlı araç bulunamadı.',
    appVersion: 'Uygulama Sürümü',
};

const culture_de = {
    account: 'MEIN KONTO',
    profileSubtitle: 'Alle Informationen an einem Ort.',
    editProfile: 'Profil bearbeiten',
    preferences: 'Einstellungen & Hilfe',
    otherVehicles: 'Weitere Fahrzeuge',
    seats: 'Plätze',
    noVehiclesSub: 'Ihre zugewiesenen Fahrzeuge werden hier angezeigt.',
    close: 'Schließen',
    retry: 'Erneut versuchen',
    loadError: 'Ihr Profil konnte nicht geladen werden.',
    connectionHint: 'Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    photoError: 'Ihr Foto konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
    cameraPermission: 'Erlauben Sie den Kamerazugriff in den Geräteeinstellungen, um ein Profilfoto aufzunehmen.',
    uploading: 'Foto wird hochgeladen',
    supportError: 'Die Hilfeseite konnte nicht geöffnet werden.',
    myProfile: 'Mein Profil',
    hello: 'Hallo',
    help: 'Hilfe',
    settings: 'Einstellungen',
    logout: 'Ausloggen',
    completed: 'Abgeschlossen',
    late: 'Spät',
    canceled: 'Abbrechen',
    vehicles: 'Fahrzeuge',
    companies: 'Firmen',
    ok: 'OK',
    driver: 'Fahrer',
    activeVehicle: 'Aktives Fahrzeug',
    usedVehicle: 'Aktives Fahrzeug',
    change: 'Ändern',
    myCars: 'Meine Fahrzeuge',
    accountSettings: 'Konto & Dokumente',
    driverInformation: 'Fahrerinformationen',
    myPersonalInformations: 'Persönliche Informationen',
    personalInfoSub: 'Name, Telefon, E-Mail & Passwort',
    myDocuments: 'Meine Dokumente',
    documentsSub: 'Fahrer- und Zulassungsdokumente',
    institutionsIServe: 'Bediente Institutionen',
    companiesSub: 'Verbundene Partnerunternehmen',
    languageSelect: 'Sprache',
    languageSub: 'App-Spracheinstellung',
    supportHelp: 'Hilfe & Support',
    supportSub: 'Kunden- & Fahrerunterstützung',
    changeProfilePhoto: 'Profilbild ändern',
    takeAPhoto: 'Foto aufnehmen',
    takePhotoSub: 'Neues Foto mit der Kamera machen',
    chooseFromLibrary: 'Aus Bibliothek wählen',
    choosePhotoSub: 'Bild aus der Galerie auswählen',
    failed: 'Fehlgeschlagen!',
    successful: 'Erfolgreich',
    useCar: 'Aktiv',
    document: 'Dokumente',
    warning: 'Abmelden',
    logOutText: 'Möchten Sie sich wirklich von Ihrem Konto abmelden?',
    rating: 'Bewertung',
    noVehicles: 'Keine Fahrzeuge registriert.',
    appVersion: 'App-Version',
};


export default { tr: culture_tr, en: culture_en, de: culture_de };
