// Odometre çekim akışının metinleri. Uygulamanın geri kalanı gibi tr / en / de destekler.

const culture_tr = {
    titleStart: 'Başlangıç Kilometresi',
    titleFinish: 'Bitiş Kilometresi',
    cameraHint: 'Kartı veya göstergeyi çerçeveye hizalayın',
    cameraSubHint: 'Yazı ve rakamların net ve okunaklı olduğundan emin olun.',
    permissionTitle: 'Kamera izni gerekli',
    permissionText: 'Kilometre bilgisini fotoğraflayabilmek için kamera iznine ihtiyacımız var.',
    permissionButton: 'İzin Ver',
    permissionSettings: 'Ayarları Aç',
    recognizing: 'Kilometre okunuyor...',
    recognizingHint: 'Fotoğraf analiz ediliyor, lütfen bekleyin.',
    submitting: 'Kaydediliyor...',
    confirmTitle: 'Okunan Kilometre',
    confirmSubtitle: 'Otomatik Algılandı',
    confirmQuestionTitle: 'Kilometre Bilgisini Onaylayın',
    confirmQuestion: 'Fotoğraftaki kilometre bilgisi doğru mu?',
    candidatesTitle: 'Doğru Kilometreyi Seçin',
    candidatesNotice: 'Birden fazla sayaç değeri algılandı. Lütfen gösterge panelinizdeki gerçek değeri aşağıdan seçin:',
    candidatesBestGuess: 'En Olası',
    candidatesScore: 'Puan',
    confirmSelectedKm: 'Seçilen Değeri Onayla',
    otherKm: 'Farklı Bir Değer Gir (Elle)',
    kmSuffix: 'km',
    lowConfidence: 'Okuma tam net değil. Lütfen değeri dikkatlice kontrol edin.',
    correct: 'Evet, Değer Doğru',
    edit: 'Değeri Düzenle',
    retake: 'Yeniden Çek',
    photoBadge: 'Çekilen Fotoğraf',
    manualTitle: 'Kilometreyi düzenle',
    manualQuestion: 'Araç kilometresini elle girin.',
    manualPlaceholder: 'Örn. 152340',
    manualApprove: 'Onayla',
    notRecognized: 'Kilometre okunamadı. Lütfen elle girin veya fotoğrafı yeniden çekin.',
    errorTitle: 'İşlem tamamlanamadı',
    captureError: 'Fotoğraf çekilemedi. Lütfen tekrar deneyin.',
    recognizeError: 'Kilometre okunamadı. Lütfen tekrar deneyin.',
    submitError: 'Kilometre kaydedilemedi. Lütfen tekrar deneyin.',
    tryAgain: 'Tekrar dene',
    enterManually: 'Elle gir',
    invalidEmpty: 'Lütfen kilometre bilgisini girin.',
    invalidNumber: 'Geçerli bir kilometre değeri girin.',
    invalidRange: 'Kilometre en fazla {max} olabilir.',
    invalidMin: 'Kilometre {min} değerinden küçük olamaz.',
    closeTitle: 'İşlemden vazgeç',
    closeText: 'Kilometre bildirimi tamamlanmadı. Çıkmak istediğinize emin misiniz?',
    closeYes: 'Çık',
    closeNo: 'Devam et',
    thousandSeparator: '.',
};

const culture_en = {
    titleStart: 'Starting Odometer',
    titleFinish: 'Ending Odometer',
    cameraHint: 'Align the card or odometer within the frame',
    cameraSubHint: 'Make sure text and digits are clear and readable.',
    permissionTitle: 'Camera permission required',
    permissionText: 'We need camera access to take a photo of the odometer.',
    permissionButton: 'Allow',
    permissionSettings: 'Open Settings',
    recognizing: 'Reading the odometer...',
    recognizingHint: 'Analyzing the photo, please wait.',
    submitting: 'Saving...',
    confirmTitle: 'Detected Odometer',
    confirmSubtitle: 'Auto Detected',
    confirmQuestionTitle: 'Confirm Odometer Value',
    confirmQuestion: 'Is the odometer value on the photo correct?',
    candidatesTitle: 'Select Correct Odometer',
    candidatesNotice: 'Multiple odometer readings detected. Please select the correct value from your dashboard:',
    candidatesBestGuess: 'Best Match',
    candidatesScore: 'Score',
    confirmSelectedKm: 'Confirm Selected Value',
    otherKm: 'Enter Another Value (Manual)',
    kmSuffix: 'km',
    lowConfidence: 'The reading is not fully clear. Please verify the value carefully.',
    correct: 'Yes, Value is Correct',
    edit: 'Edit Value',
    retake: 'Retake Photo',
    photoBadge: 'Captured Photo',
    manualTitle: 'Edit the odometer',
    manualQuestion: 'Enter the vehicle odometer manually.',
    manualPlaceholder: 'e.g. 152340',
    manualApprove: 'Confirm',
    notRecognized: 'The odometer could not be read. Please enter it manually or retake the photo.',
    errorTitle: 'Could not complete',
    captureError: 'The photo could not be taken. Please try again.',
    recognizeError: 'The odometer could not be read. Please try again.',
    submitError: 'The odometer could not be saved. Please try again.',
    tryAgain: 'Try again',
    enterManually: 'Enter manually',
    invalidEmpty: 'Please enter the odometer value.',
    invalidNumber: 'Enter a valid odometer value.',
    invalidRange: 'The odometer can be at most {max}.',
    invalidMin: 'The odometer cannot be lower than {min}.',
    closeTitle: 'Cancel the step',
    closeText: 'The odometer has not been submitted. Are you sure you want to leave?',
    closeYes: 'Leave',
    closeNo: 'Continue',
    thousandSeparator: ',',
};

const culture_de = {
    titleStart: 'Kilometerstand bei Beginn',
    titleFinish: 'Kilometerstand bei Ende',
    cameraHint: 'Karte oder Kilometerzähler im Rahmen ausrichten',
    cameraSubHint: 'Achten Sie darauf, dass Ziffern und Text gut lesbar sind.',
    permissionTitle: 'Kamerazugriff erforderlich',
    permissionText: 'Wir benötigen Kamerazugriff, um den Kilometerstand zu fotografieren.',
    permissionButton: 'Erlauben',
    permissionSettings: 'Einstellungen öffnen',
    recognizing: 'Kilometerstand wird gelesen...',
    recognizingHint: 'Das Foto wird analysiert, bitte warten.',
    submitting: 'Wird gespeichert...',
    confirmTitle: 'Erkannter Kilometerstand',
    confirmSubtitle: 'Automatisch erkannt',
    confirmQuestionTitle: 'Kilometerstand bestätigen',
    confirmQuestion: 'Ist der Kilometerstand auf dem Foto korrekt?',
    candidatesTitle: 'Richtigen Kilometerstand wählen',
    candidatesNotice: 'Mehrere Werte erkannt. Bitte wählen Sie den korrekten Wert Ihres Armaturenbretts:',
    candidatesBestGuess: 'Beste Übereinstimmung',
    candidatesScore: 'Punktzahl',
    confirmSelectedKm: 'Ausgewählten Wert bestätigen',
    otherKm: 'Anderen Wert manuell eingeben',
    kmSuffix: 'km',
    lowConfidence: 'Die Erkennung ist unsicher. Bitte prüfen Sie den Wert sorgfältig.',
    correct: 'Ja, Wert ist korrekt',
    edit: 'Wert bearbeiten',
    retake: 'Neu aufnehmen',
    photoBadge: 'Aufgenommenes Foto',
    manualTitle: 'Kilometerstand bearbeiten',
    manualQuestion: 'Geben Sie den Kilometerstand manuell ein.',
    manualPlaceholder: 'z. B. 152340',
    manualApprove: 'Bestätigen',
    notRecognized: 'Der Kilometerstand konnte nicht gelesen werden. Bitte manuell eingeben oder neu aufnehmen.',
    errorTitle: 'Vorgang nicht abgeschlossen',
    captureError: 'Das Foto konnte nicht aufgenommen werden. Bitte erneut versuchen.',
    recognizeError: 'Der Kilometerstand konnte nicht gelesen werden. Bitte erneut versuchen.',
    submitError: 'Der Kilometerstand konnte nicht gespeichert werden. Bitte erneut versuchen.',
    tryAgain: 'Erneut versuchen',
    enterManually: 'Manuell eingeben',
    invalidEmpty: 'Bitte geben Sie den Kilometerstand ein.',
    invalidNumber: 'Geben Sie einen gültigen Kilometerstand ein.',
    invalidRange: 'Der Kilometerstand darf höchstens {max} betragen.',
    invalidMin: 'Der Kilometerstand darf nicht kleiner als {min} sein.',
    closeTitle: 'Schritt abbrechen',
    closeText: 'Der Kilometerstand wurde nicht übermittelt. Möchten Sie wirklich abbrechen?',
    closeYes: 'Abbrechen',
    closeNo: 'Fortfahren',
    thousandSeparator: '.',
};

export default function getOdometerTexts(culture) {
    if (culture === 'en') return culture_en;
    if (culture === 'de') return culture_de;
    return culture_tr;
}
