const ListCulture = {
    culture_en: {
        ok: 'OK',
        headerTextNotAvailable: 'I am busy',
        headerTextAvailable: 'I am available',
        completed: 'COMPLETED',
        transferType1: 'One Way Trip',
        transferType2: 'Round Trip',
        transferType3: 'Private Driver',
        transferType4: 'Shuttle',
        transfer: 'TRANSFER',
        distance: 'DISTANCE',
        duration: 'DURATION',
        passenger: 'Passenger',
        payment: 'PAYMENT',
        start1: 'Start',
        finish: 'Finish',
        amount: 'Amount',
        driverNote: 'Driver Note',
        sendFollowLink: 'Send Follow Link',
        addAdditionalService: 'Add Additional Service',
        dropTransfer: 'Drop Transfer',
        startLocation: 'STARTING POINT',
        pickupLocation: 'BOARDING POINT',
        dropLocation: 'LANDING POINT',
        company: 'Company',
        flightCode: 'Flight Code',
        situation: 'Situation',
        note: 'Greeter Note',
        waypointLocation: 'WAYPOINT',
        endLocation: 'ENDPOINT',
        waypointSingle: 'Waypoint',
        waypointMulti: 'Waypoints',
        trackingLink: 'Send Tracking Link',
        more: 'More',
        allTransfers: 'All transfers',
        waiting: 'Waiting for approval',
        completedTransfers: 'Upcoming',
        approve: 'Accept',
        deny: 'Reject',
        canceled: 'Canceled',
        noshow: 'No-Show',
        willBegin: 'Will begin',
        hasCompleted: 'Completed',
        boarded: 'Boarded the Vehicle',
        departed: 'Got Out of the Vehicle',
        arrived: 'Reached the Stop',
        late: 'Late',
        started: 'Started',
        passengerRecieved: 'Passenger recieved',
        notCompleted: 'Not completed',
        start: 'Start driving',
        continue: 'Continue driving',
        sendFollowLink: "Send Follow Link",
        show: 'SHOW',
        noUetds: 'No U-ETDS certificate',
        uetds: 'U-ETDS certificate available',
        create: 'CREATE',
        startDriving: 'Start driving',
        startDrivingText: 'Start driving as the first step.',
        finishDrivingText: 'Finish to complete the ride',
        navigate: 'Get Directions',
        finishWork: 'Finish',
        passengerSuccess: 'Congratulations! You reached the address and the passenger got into your vehicle. Please continue with the next step.',
        passengerDropSuccess: 'Congratulations! You reached the address and the passenger got out of your vehicle. Please continue with the next step.',
        waypointSuccess: 'Congratulations! You reached the address. Please continue with the next step.',
        completeMessage: 'Congratulations! You have complete the ride. Please check alternative rides available for you.',
        undo: 'Undo action',
        locationPermissionTitle: 'vitaDrive Transfer requests your location',
        locationPermissionText: 'vitaDrive Transfer uses your location to track your driving performance and distance you make for the rides we send when the app is in background',
        foregroundPermissionText: "In order to use vitaDrive Transfer in a healthier way, please allow location services as always in your device's settings.",
        locationPermissionButton: 'Allways Allow',
        foregroundPermissionButton: 'OK',
        usingLocationTitle: 'vitaDrive Transfer is running in the background',
        usingLocationSubTitle: 'We track your location in real time.',
        delay: 'min delay',
        timer: 'on time',
        transferLeave: 'Are you sure you want to abandon the transfer?',
        yesButton: 'Yes',
        noButton: 'No',
        warning: 'Warning',
        leavedTransfer: 'Transfer has been successfully abandoned',
        failed: 'Failed!',
        successful: 'Successful',
        notBoarded: "Passengers didn't arrive",



        modalSuccessMessage: 'Your break request has been received.',
        modalFinishMessage: 'The break has ended. Have a safe journey.',
        useBreakTime: 'Use Break',
        optionsText: 'Please select the reason for your break request',
        finishBreakTime: 'End Break',
        used: 'Used',
        startBreakTime: 'Start',
    },
    culture_tr: {
        ok: 'Tamam',
        headerTextNotAvailable: 'Şu an meşgulüm',
        headerTextAvailable: 'Şu an müsaitim',
        completed: 'TAMAMLANAN',
        transferType1: 'Tek Yön Transfer',
        transferType2: 'Çift Yön',
        transferType3: 'Tahsis',
        transferType4: 'Shuttle',
        transfer: 'TRANSFER',
        distance: 'MESAFE',
        duration: 'SÜRE',
        passenger: 'Yolcu',
        payment: 'ÖDEME',
        start1: 'Başlangıç',
        finish: 'Bitiş',
        amount: 'Tutar',
        driverNote: 'Sürücü Notu',
        sendFollowLink: 'Takip Linki Gönder',
        addAdditionalService: 'Ek Hizmet Ekle',
        dropTransfer: 'Transferi Bırak',
        company: 'Firma',
        flightCode: 'Uçuş Kodu',
        situation: 'Durum',
        note: 'Karşılama Notu',
        startLocation: 'BAŞLANGIÇ NOKTASI',
        endLocation: 'BİTİŞ NOKTASI',
        pickupLocation: 'ALINIŞ NOKTASI',
        dropLocation: 'BIRAKILIŞ NOKTASI',
        waypointLocation: 'DURAK NOKTASI',
        waypointSingle: 'Durak',
        waypointMulti: 'Durak',
        trackingLink: 'Takip Linki Gönder',
        more: 'Daha fazla',
        allTransfers: 'Tüm transferler',
        waiting: 'Onay bekleyenler',
        completedTransfers: 'Yaklaşanlar',
        approve: 'Kabul Et',
        deny: 'Reddet',
        noshow: 'Yolcu gelmedi',
        canceled: 'İptal edildi',
        willBegin: 'Başlayacak',
        hasCompleted: 'Tamamlandı',
        boarded: 'Yolcular Bindi',
        notBoarded: 'Yolcular Gelmedi',
        departed: 'Yolcular İndi',
        arrived: 'Durağa Vardım',
        late: 'Gecikti',
        started: 'Başladı',
        passengerRecieved: 'Yolcu alındı',
        notCompleted: 'Tamamlanmadı',
        start: 'Sürüşe Başla',
        continue: 'Sürüşe devam et',
        sendFollowLink: "Takip Linki Gönder",
        show: 'GÖRÜNTÜLE',
        noUetds: 'U-ETDS belgesi oluşturulmadı',
        uetds: 'U-ETDS belgesi mevcut',
        create: 'OLUŞTUR',
        startDriving: 'Sürüşe başlayın',
        startDrivingText: 'İlk adım olarak transferi başlatın.',
        finishDrivingText: 'Transferi sonlandırmak için hizmeti bitirin.',
        navigate: 'Yol Tarifi Al',
        finishWork: 'Bitir',
        passengerSuccess: 'Tebrikler! Adrese ulaştınız ve yolcu aracınıza bindi. Lütfen sonraki adımdan devam edin.',
        passengerDropSuccess: 'Tebrikler! Adrese ulaştınız ve yolcu aracınızdan indi. Lütfen sonraki adımdan devam edin.',
        waypointSuccess: 'Tebrikler! Adrese ulaştınız. Lütfen sonraki adımdan devam edin.',
        completeMessage: 'Tebrikler! Sürüşü tamamladınız. Lütfen size uygun alternatif işleri kontrol edin.',
        undo: 'İşlemi geri al',
        locationPermissionTitle: 'vitaDrive Transfer konum erişim izni',
        locationPermissionText: 'vitaDrive Transfer, uygulama arka plandayken sürüş performansınızı ve gönderdiğimiz yolculuklar için yaptığınız mesafeyi takip etmek için konumunuzu kullanır.',
        foregroundPermissionText: 'vitaDrive Transfer i daha sağlıklı kullanmak için lütfen cihazınızın ayarlar bölümünden konum servislerine her zaman olacak şekilde izin verin',
        locationPermissionButton: 'Her Zaman İzin Ver',
        foregroundPermissionButton: 'Tamam',
        usingLocationTitle: 'vitaDrive Transfer arkaplanda çalışıyor',
        usingLocationSubTitle: 'Konumunuzu gerçek zamanlı olarak takip ediyoruz.',
        delay: 'DK gecikme',
        timer: 'Zamanında',
        transferLeave: 'Transferi bırakmak istediğinize emin misiniz?',
        yesButton: 'Evet',
        noButton: 'Hayır',
        warning: 'Uyarı',
        leavedTransfer: ' Transfer başarıyla bırakılmıştır.',
        failed: 'Başarısız!',
        successful: 'Başarılı',





        modalSuccessMessage: 'Mola kullanma talebiniz alınmıştır.',
        modalFinishMessage: 'Mola sonlandırılmıştır. İyi yolculuklar.',
        useBreakTime: 'Mola Kullanımı',
        optionsText: 'Lütfen mola talebinizin sebebini seçin',
        finishBreakTime: 'Molayı Bitir',
        used: 'Kullanıldı',
        startBreakTime: 'Başla',
    },
    culture_de: {
        ok: 'OK',
        headerTextNotAvailable: 'Ich fahre',
        headerTextAvailable: 'Ich bin verfügbar',
        completed: 'ABGESCHLOSSEN',
        transferType1: 'Einwegtrip',
        transferType2: 'Rundfahrt',
        transferType3: 'Chauffeur',
        transferType4: 'Shuttlebus',
        transfer: 'überweisen',
        distance: 'DISTANZ',
        duration: 'DAUER',
        passenger: 'Passagier',
        payment: 'ZAHLUNG',
        start1: 'Start',
        finish: 'Beenden',
        amount: 'Menge',
        driverNote: 'Fahrerhinweis',
        sendFollowLink: 'Senden Folgen Verknüpfung',
        addAdditionalService: 'Zusätzlichen Service hinzufügen',
        dropTransfer: 'Drop-Transfer',
        company: 'Unternehmen',
        flightCode: 'Flugcode',
        situation: 'Situation',
        note: 'Begrüßungsnotiz',
        startLocation: 'STARTPUNKT',
        endLocation: 'ENDPUNKT',
        pickupLocation: 'EINSTIEGSPUNKT',
        dropLocation: 'LANDEPUNKT',
        waypointLocation: 'WEGPUNKT',
        waypointSingle: 'Haltestelle',
        waypointMulti: 'Haltestellen',
        trackingLink: 'Tracking-Link Senden',
        more: 'Mehr',
        allTransfers: 'Alle überweisungen',
        waiting: 'Warten auf die Bestätigung',
        completedTransfers: 'Bevorstehende',
        approve: 'Annehmen',
        deny: 'Ablehnen',
        canceled: 'Abgesagt',
        noshow: 'Kam nicht',
        willBegin: 'Wird beginnen',
        hasCompleted: 'Abgeschlossen',
        boarded: 'Passagiere stiegen ein',
        departed: 'Passagiere stiegen aus',
        arrived: 'Haltestelle erreicht',
        late: 'Verspätet',
        started: 'Gestartet',
        passengerRecieved: 'Passagier genommen',
        notCompleted: 'Nicht vollständig',
        start: 'Losfahren',
        continue: 'Fahr weiter',
        sendFollowLink: "Follow-Link Senden",
        show: 'ZEIGEN',
        noUetds: 'Kein UETDS-Zertifikat',
        uetds: 'UETDS-Zertifikat haben',
        create: 'ERSTELLEN',
        startDriving: 'Losfahren',
        startDrivingText: 'Beginnen Sie mit dem Fahren als erster Schritt',
        finishDrivingText: 'Beenden Sie die Fahrt',
        navigate: 'Route berechnen',
        finishWork: 'Fertig',
        passengerSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht und der Beifahrer ist in Ihr Fahrzeug eingestiegen. Bitte fahren Sie mit dem nächsten Schritt fort.',
        passengerDropSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht und der Beifahrer ist aus Ihrem Fahrzeug ausgestiegen. Bitte fahren Sie mit dem nächsten Schritt fort.',
        waypointSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht. Bitte fahren Sie mit dem nächsten Schritt fort.',
        completeMessage: 'Herzliche Glückwünsche! Sie haben die Fahrt abgeschlossen. Bitte überprüfen Sie die für Sie verfügbaren alternativen Fahrten.',
        undo: 'Aktion rückgängig machen',
        locationPermissionTitle: 'vitaDrive Transfer fragt Ihren Standort ab',
        locationPermissionText: 'vitaDrive Transfer fordert Ihren Standort an, um Ihre Fahrleistung und Distanz zu verfolgen, die Sie für die Fahrten zurücklegen, die wir senden, wenn die App im Hintergrund läuft',
        foregroundPermissionText: 'Um vitaDrive Transfer gesünder nutzen zu können, erlauben Sie bitte immer Ortungsdienste im Einstellungsbereich Ihres Geräts.',
        locationPermissionButton: 'Immer zulassen',
        foregroundPermissionButton: 'Fertig',
        usingLocationTitle: 'vitaDrive Transfer läuft im Hintergrund',
        usingLocationSubTitle: 'Wir tracken Ihren Standort in Echtzeit.',
        delay: 'min Verzögerung',
        timer: 'pünktlich',
        transferLeave: 'Möchten Sie den Transfer wirklich abbrechen?',
        yesButton: 'Ja',
        noButton: 'Nein',
        warning: 'Warnung',
        leavedTransfer: 'Die Übertragung wurde erfolgreich abgebrochen.',
        failed: 'Fehlgeschlagen!',
        successful: 'Erfolgreich',
        notBoarded: "Die Passagiere sind nicht angekommen",

        modalSuccessMessage: 'Ihre Pausenanforderung wurde erhalten.',
        modalFinishMessage: 'Die Pause wurde beendet. Gute Fahrt.',
        useBreakTime: 'Pause nutzen',
        optionsText: 'Bitte wählen Sie den Grund für Ihre Pausenanforderung',
        finishBreakTime: 'Pause beenden',
        used: 'Verwendet',
        startBreakTime: 'Starten',

    }

        // const culture_en = {
        //   ok: 'OK',
        //   headerTextNotAvailable: 'I am busy',
        //   headerTextAvailable: 'I am available',
        //   completed: 'COMPLETED',
        //   transferType1: 'One Way Trip',
        //   transferType2: 'Round Trip',
        //   transferType3: 'Private Driver',
        //   transferType4: 'Shuttle',
        //   transfer: 'TRANSFER',
        //   distance: 'DISTANCE',
        //   duration: 'DURATION',
        //   passenger: 'Passenger',
        //   payment: 'PAYMENT',
        //   start1: 'Start',
        //   finish: 'Finish',
        //   amount: 'Amount',
        //   driverNote: 'Driver Note',
        //   sendFollowLink: 'Send Follow Link',
        //   addAdditionalService: 'Add Additional Service',
        //   dropTransfer: 'Drop Transfer',
        //   startLocation: 'STARTING POINT',
        //   pickupLocation: 'BOARDING POINT',
        //   dropLocation: 'LANDING POINT',
        //   company: 'Company',
        //   flightCode: 'Flight Code',
        //   situation: 'Situation',
        //   note: 'Greeter Note',
        //   waypointLocation: 'WAYPOINT',
        //   endLocation: 'ENDPOINT',
        //   waypointSingle: 'Waypoint',
        //   waypointMulti: 'Waypoints',
        //   trackingLink: 'Send Tracking Link',
        //   more: 'More',
        //   allTransfers: 'All transfers',
        //   waiting: 'Waiting for approval',
        //   completedTransfers: 'Upcoming',
        //   approve: 'Accept',
        //   deny: 'Reject',
        //   canceled: 'Canceled',
        //   noshow: 'No-Show',
        //   willBegin: 'Will begin',
        //   hasCompleted: 'Completed',
        //   boarded: 'Boarded the Vehicle',
        //   departed: 'Got Out of the Vehicle',
        //   arrived: 'Reached the Stop',
        //   late: 'Late',
        //   started: 'Started',
        //   passengerRecieved: 'Passenger recieved',
        //   notCompleted: 'Not completed',
        //   start: 'Start driving',
        //   continue: 'Continue driving',
        //   sendFollowLink: "Send Follow Link",
        //   show: 'SHOW',
        //   noUetds: 'No U-ETDS certificate',
        //   uetds: 'U-ETDS certificate available',
        //   create: 'CREATE',
        //   startDriving: 'Start driving',
        //   startDrivingText: 'Start driving as the first step.',
        //   finishDrivingText: 'Finish to complete the ride',
        //   navigate: 'Get Directions',
        //   finishWork: 'Finish',
        //   passengerSuccess: 'Congratulations! You reached the address and the passenger got into your vehicle. Please continue with the next step.',
        //   passengerDropSuccess: 'Congratulations! You reached the address and the passenger got out of your vehicle. Please continue with the next step.',
        //   waypointSuccess: 'Congratulations! You reached the address. Please continue with the next step.',
        //   completeMessage: 'Congratulations! You have complete the ride. Please check alternative rides available for you.',
        //   undo: 'Undo action',
        //   locationPermissionTitle: 'vitaDrive Transfer requests your location',
        //   locationPermissionText: 'vitaDrive Transfer uses your location to track your driving performance and distance you make for the rides we send when the app is in background',
        //   foregroundPermissionText: "In order to use vitaDrive Transfer in a healthier way, please allow location services as always in your device's settings.",
        //   locationPermissionButton: 'Allways Allow',
        //   foregroundPermissionButton: 'OK',
        //   usingLocationTitle: 'vitaDrive Transfer is running in the background',
        //   usingLocationSubTitle: 'We track your location in real time.',
        //   delay: 'min delay',
        //   timer: 'on time',
        //   transferLeave: 'Are you sure you want to abandon the transfer?',
        //   yesButton: 'Yes',
        //   noButton: 'No',
        //   warning: 'Warning',
        //   leavedTransfer: 'Transfer has been successfully abandoned',
        //   failed: 'Failed!',
        //   successful: 'Successful',
        //   notBoarded: "Passengers didn't arrive",
    
    
    
        //   modalSuccessMessage: 'Your break request has been received.',
        //   modalFinishMessage: 'The break has ended. Have a safe journey.',
        //   useBreakTime: 'Use Break',
        //   optionsText: 'Please select the reason for your break request',
        //   finishBreakTime: 'End Break',
        //   used: 'Used',
        //   startBreakTime: 'Start',
    
        // }
        // const culture_tr = {
        //   ok: 'Tamam',
        //   headerTextNotAvailable: 'Şu an meşgulüm',
        //   headerTextAvailable: 'Şu an müsaitim',
        //   completed: 'TAMAMLANAN',
        //   transferType1: 'Tek Yön Transfer',
        //   transferType2: 'Çift Yön',
        //   transferType3: 'Tahsis',
        //   transferType4: 'Shuttle',
        //   transfer: 'TRANSFER',
        //   distance: 'MESAFE',
        //   duration: 'SÜRE',
        //   passenger: 'Yolcu',
        //   payment: 'ÖDEME',
        //   start1: 'Başlangıç',
        //   finish: 'Bitiş',
        //   amount: 'Tutar',
        //   driverNote: 'Sürücü Notu',
        //   sendFollowLink: 'Takip Linki Gönder',
        //   addAdditionalService: 'Ek Hizmet Ekle',
        //   dropTransfer: 'Transferi Bırak',
        //   company: 'Firma',
        //   flightCode: 'Uçuş Kodu',
        //   situation: 'Durum',
        //   note: 'Karşılama Notu',
        //   startLocation: 'BAŞLANGIÇ NOKTASI',
        //   endLocation: 'BİTİŞ NOKTASI',
        //   pickupLocation: 'ALINIŞ NOKTASI',
        //   dropLocation: 'BIRAKILIŞ NOKTASI',
        //   waypointLocation: 'DURAK NOKTASI',
        //   waypointSingle: 'Durak',
        //   waypointMulti: 'Durak',
        //   trackingLink: 'Takip Linki Gönder',
        //   more: 'Daha fazla',
        //   allTransfers: 'Tüm transferler',
        //   waiting: 'Onay bekleyenler',
        //   completedTransfers: 'Yaklaşanlar',
        //   approve: 'Kabul Et',
        //   deny: 'Reddet',
        //   noshow: 'Yolcu gelmedi',
        //   canceled: 'İptal edildi',
        //   willBegin: 'Başlayacak',
        //   hasCompleted: 'Tamamlandı',
        //   boarded: 'Yolcular Bindi',
        //   notBoarded: 'Yolcular Gelmedi',
        //   departed: 'Yolcular İndi',
        //   arrived: 'Durağa Vardım',
        //   late: 'Gecikti',
        //   started: 'Başladı',
        //   passengerRecieved: 'Yolcu alındı',
        //   notCompleted: 'Tamamlanmadı',
        //   start: 'Sürüşe Başla',
        //   continue: 'Sürüşe devam et',
        //   sendFollowLink: "Takip Linki Gönder",
        //   show: 'GÖRÜNTÜLE',
        //   noUetds: 'U-ETDS belgesi oluşturulmadı',
        //   uetds: 'U-ETDS belgesi mevcut',
        //   create: 'OLUŞTUR',
        //   startDriving: 'Sürüşe başlayın',
        //   startDrivingText: 'İlk adım olarak transferi başlatın.',
        //   finishDrivingText: 'Transferi sonlandırmak için hizmeti bitirin.',
        //   navigate: 'Yol Tarifi Al',
        //   finishWork: 'Bitir',
        //   passengerSuccess: 'Tebrikler! Adrese ulaştınız ve yolcu aracınıza bindi. Lütfen sonraki adımdan devam edin.',
        //   passengerDropSuccess: 'Tebrikler! Adrese ulaştınız ve yolcu aracınızdan indi. Lütfen sonraki adımdan devam edin.',
        //   waypointSuccess: 'Tebrikler! Adrese ulaştınız. Lütfen sonraki adımdan devam edin.',
        //   completeMessage: 'Tebrikler! Sürüşü tamamladınız. Lütfen size uygun alternatif işleri kontrol edin.',
        //   undo: 'İşlemi geri al',
        //   locationPermissionTitle: 'vitaDrive Transfer konum erişim izni',
        //   locationPermissionText: 'vitaDrive Transfer, uygulama arka plandayken sürüş performansınızı ve gönderdiğimiz yolculuklar için yaptığınız mesafeyi takip etmek için konumunuzu kullanır.',
        //   foregroundPermissionText: 'vitaDrive Transfer i daha sağlıklı kullanmak için lütfen cihazınızın ayarlar bölümünden konum servislerine her zaman olacak şekilde izin verin',
        //   locationPermissionButton: 'Her Zaman İzin Ver',
        //   foregroundPermissionButton: 'Tamam',
        //   usingLocationTitle: 'vitaDrive Transfer arkaplanda çalışıyor',
        //   usingLocationSubTitle: 'Konumunuzu gerçek zamanlı olarak takip ediyoruz.',
        //   delay: 'DK gecikme',
        //   timer: 'Zamanında',
        //   transferLeave: 'Transferi bırakmak istediğinize emin misiniz?',
        //   yesButton: 'Evet',
        //   noButton: 'Hayır',
        //   warning: 'Uyarı',
        //   leavedTransfer: ' Transfer başarıyla bırakılmıştır.',
        //   failed: 'Başarısız!',
        //   successful: 'Başarılı',
    
    
        //   modalSuccessMessage: 'Mola kullanma talebiniz alınmıştır.',
        //   modalFinishMessage: 'Mola sonlandırılmıştır. İyi yolculuklar.',
        //   useBreakTime: 'Mola Kullanımı',
        //   optionsText: 'Lütfen mola talebinizin sebebini seçin',
        //   finishBreakTime: 'Molayı Bitir',
        //   used: 'Kullanıldı',
        //   startBreakTime: 'Başla',
        // }
        // const culture_de = {
        //   ok: 'OK',
        //   headerTextNotAvailable: 'Ich fahre',
        //   headerTextAvailable: 'Ich bin verfügbar',
        //   completed: 'ABGESCHLOSSEN',
        //   transferType1: 'Einwegtrip',
        //   transferType2: 'Rundfahrt',
        //   transferType3: 'Chauffeur',
        //   transferType4: 'Shuttlebus',
        //   transfer: 'überweisen',
        //   distance: 'DISTANZ',
        //   duration: 'DAUER',
        //   passenger: 'Passagier',
        //   payment: 'ZAHLUNG',
        //   start1: 'Start',
        //   finish: 'Beenden',
        //   amount: 'Menge',
        //   driverNote: 'Fahrerhinweis',
        //   sendFollowLink: 'Senden Folgen Verknüpfung',
        //   addAdditionalService: 'Zusätzlichen Service hinzufügen',
        //   dropTransfer: 'Drop-Transfer',
        //   company: 'Unternehmen',
        //   flightCode: 'Flugcode',
        //   situation: 'Situation',
        //   note: 'Begrüßungsnotiz',
        //   startLocation: 'STARTPUNKT',
        //   endLocation: 'ENDPUNKT',
        //   pickupLocation: 'EINSTIEGSPUNKT',
        //   dropLocation: 'LANDEPUNKT',
        //   waypointLocation: 'WEGPUNKT',
        //   waypointSingle: 'Haltestelle',
        //   waypointMulti: 'Haltestellen',
        //   trackingLink: 'Tracking-Link Senden',
        //   more: 'Mehr',
        //   allTransfers: 'Alle überweisungen',
        //   waiting: 'Warten auf die Bestätigung',
        //   completedTransfers: 'Bevorstehende',
        //   approve: 'Annehmen',
        //   deny: 'Ablehnen',
        //   canceled: 'Abgesagt',
        //   noshow: 'Kam nicht',
        //   willBegin: 'Wird beginnen',
        //   hasCompleted: 'Abgeschlossen',
        //   boarded: 'Passagiere stiegen ein',
        //   departed: 'Passagiere stiegen aus',
        //   arrived: 'Haltestelle erreicht',
        //   late: 'Verspätet',
        //   started: 'Gestartet',
        //   passengerRecieved: 'Passagier genommen',
        //   notCompleted: 'Nicht vollständig',
        //   start: 'Losfahren',
        //   continue: 'Fahr weiter',
        //   sendFollowLink: "Follow-Link Senden",
        //   show: 'ZEIGEN',
        //   noUetds: 'Kein UETDS-Zertifikat',
        //   uetds: 'UETDS-Zertifikat haben',
        //   create: 'ERSTELLEN',
        //   startDriving: 'Losfahren',
        //   startDrivingText: 'Beginnen Sie mit dem Fahren als erster Schritt',
        //   finishDrivingText: 'Beenden Sie die Fahrt',
        //   navigate: 'Route berechnen',
        //   finishWork: 'Fertig',
        //   passengerSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht und der Beifahrer ist in Ihr Fahrzeug eingestiegen. Bitte fahren Sie mit dem nächsten Schritt fort.',
        //   passengerDropSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht und der Beifahrer ist aus Ihrem Fahrzeug ausgestiegen. Bitte fahren Sie mit dem nächsten Schritt fort.',
        //   waypointSuccess: 'Herzliche Glückwünsche! Sie haben die Adresse erreicht. Bitte fahren Sie mit dem nächsten Schritt fort.',
        //   completeMessage: 'Herzliche Glückwünsche! Sie haben die Fahrt abgeschlossen. Bitte überprüfen Sie die für Sie verfügbaren alternativen Fahrten.',
        //   undo: 'Aktion rückgängig machen',
        //   locationPermissionTitle: 'vitaDrive Transfer fragt Ihren Standort ab',
        //   locationPermissionText: 'vitaDrive Transfer fordert Ihren Standort an, um Ihre Fahrleistung und Distanz zu verfolgen, die Sie für die Fahrten zurücklegen, die wir senden, wenn die App im Hintergrund läuft',
        //   foregroundPermissionText: 'Um vitaDrive Transfer gesünder nutzen zu können, erlauben Sie bitte immer Ortungsdienste im Einstellungsbereich Ihres Geräts.',
        //   locationPermissionButton: 'Immer zulassen',
        //   foregroundPermissionButton: 'Fertig',
        //   usingLocationTitle: 'vitaDrive Transfer läuft im Hintergrund',
        //   usingLocationSubTitle: 'Wir tracken Ihren Standort in Echtzeit.',
        //   delay: 'min Verzögerung',
        //   timer: 'pünktlich',
        //   transferLeave: 'Möchten Sie den Transfer wirklich abbrechen?',
        //   yesButton: 'Ja',
        //   noButton: 'Nein',
        //   warning: 'Warnung',
        //   leavedTransfer: 'Die Übertragung wurde erfolgreich abgebrochen.',
        //   failed: 'Fehlgeschlagen!',
        //   successful: 'Erfolgreich',
        //   notBoarded: "Die Passagiere sind nicht angekommen",
    
    
        //   modalSuccessMessage: 'Ihre Pausenanforderung wurde erhalten.',
        //   modalFinishMessage: 'Die Pause wurde beendet. Gute Fahrt.',
        //   useBreakTime: 'Pause nutzen',
        //   optionsText: 'Bitte wählen Sie den Grund für Ihre Pausenanforderung',
        //   finishBreakTime: 'Pause beenden',
        //   used: 'Verwendet',
        //   startBreakTime: 'Starten',
        // }
}
export default ListCulture